title: Zed Laboratories
description: Bookmark this to keep an eye on my project updates!

# theme: jekyll-theme-merlot
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: true
