title: Zed Laboratories
description: GitHub Page description

# remote_theme: pages-themes/merlot@v0.2.0
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
